name: Telegram Bot Cronjob

on:
  schedule:
    # Morning (07:00 WIB)
    - cron: "0 0 * * 1-5"
    # Sydney (05:00 WIB)
    - cron: "0 22 * * 0-4"
    # Tokyo (07:00 WIB)
    - cron: "0 0 * * 1-5"
    # London (13:00 WIB)
    - cron: "0 6 * * 1-5"
    # New York (20:00 WIB)
    - cron: "0 13 * * 1-5"
   

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Sydney Session
        run: curl "https://telebot-xi-sable.vercel.app/api?task=sydney"
      - name: Call Tokyo Session
        run: curl "https://telebot-xi-sable.vercel.app/api?task=tokyo"
      - name: Call London Session
        run: curl "https://telebot-xi-sable.vercel.app/api?task=london"
      - name: Call New York Session
        run: curl "https://telebot-xi-sable.vercel.app/api?task=newyork"
      - name: Call Morning Message
        run: curl "https://telebot-xi-sable.vercel.app/api?task=morning"
